if(NOT DEFINED PROTOBUF_SOURCE_DIR)
  message(FATAL_ERROR "PROTOBUF_SOURCE_DIR is required")
endif()

set(PROTOBUF_CMAKE_LISTS "${PROTOBUF_SOURCE_DIR}/cmake/CMakeLists.txt")
file(READ "${PROTOBUF_CMAKE_LISTS}" PROTOBUF_CONTENTS)

set(STATIC_RUNTIME "set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded$<$<CONFIG:Debug>:Debug>)")
set(DYNAMIC_RUNTIME "set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded$<$<CONFIG:Debug>:Debug>DLL)")
string(FIND "${PROTOBUF_CONTENTS}" "${STATIC_RUNTIME}" STATIC_RUNTIME_OFFSET)
if(STATIC_RUNTIME_OFFSET EQUAL -1)
  message(FATAL_ERROR "Expected protobuf static MSVC runtime setting was not found")
endif()

string(REPLACE "${STATIC_RUNTIME}" "${DYNAMIC_RUNTIME}" PROTOBUF_CONTENTS "${PROTOBUF_CONTENTS}")
file(WRITE "${PROTOBUF_CMAKE_LISTS}" "${PROTOBUF_CONTENTS}")
